=== asim-jaweesh/odz/doc/vuln.xsd
<?xml version="1.0" encoding="UTF-8"?>

<!--

-->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:simpleType name="stringtype">
    <xs:restriction base="xs:string">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="uritype">
    <xs:restriction base="xs:anyURI">
      <xs:minLength value="1" />
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="typetype">
    <xs:restriction base="stringtype">
      <xs:enumeration value="SQLI"/>
      <xs:enumeration value="MULTI"/>
      <xs:enumeration value="REDIRECT"/>
      <xs:enumeration value="RCE"/>
      <xs:enumeration value="RFI"/>
      <xs:enumeration value="LFI"/>
      <xs:enumeration value="UPLOAD"/>
      <xs:enumeration value="UNKNOWN"/>
      <xs:enumeration value="XSS"/>
      <xs:enumeration value="CSRF"/>
      <xs:enumeration value="AUTHBYPASS"/>
      <xs:enumeration value="FPD"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:complexType name="itemtype">
    <xs:sequence>
      <xs:element name="vulnerability" type="vulntype" maxOccurs="unbounded" minOccurs="1" />
    </xs:sequence>
    <xs:attribute type="stringtype" name="name" use="required"/>
  </xs:complexType>

  <xs:complexType name="wordpresstype">
    <xs:sequence>
      <xs:element name="vulnerability" type="vulntype" maxOccurs="unbounded" minOccurs="1" />
    </xs:sequence>
    <xs:attribute type="stringtype" name="version" use="required"/>
  </xs:complexType>

  <xs:complexType name="vulntype">
    <xs:sequence minOccurs="1" maxOccurs="1">
      <xs:element name="title" type="stringtype"/>
      <xs:element name="reference" type="uritype" maxOccurs="unbounded" minOccurs="1"/>
      <xs:element name="metasploit" type="stringtype" maxOccurs="unbounded" minOccurs="0"/>
      <xs:element name="type" type="typetype"/>
    </xs:sequence>
  </xs:complexType>

  <xs:element name="vulnerabilities">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="plugin" type="itemtype" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element name="theme" type="itemtype" maxOccurs="unbounded" minOccurs="0"/>
        <xs:element name="wordpress" type="wordpresstype" maxOccurs="unbounded" minOccurs="0"/>
      </xs:sequence>
    </xs:complexType>
    <xs:unique name="uniquePlugin">
      <xs:selector xpath="plugin"/>
      <xs:field xpath="@name"/>
    </xs:unique>
    <xs:unique name="uniqueTheme">
      <xs:selector xpath="theme"/>
      <xs:field xpath="@name"/>
    </xs:unique>
    <xs:unique name="uniqueWordpress">
      <xs:selector xpath="wordpress"/>
      <xs:field xpath="@version"/>
    </xs:unique>
  </xs:element>

</xs:schema>

=== asim-jaweesh/odz/doc/theme_vulns.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--

-->

<vulnerabilities xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:noNamespaceSchemaLocation="vuln.xsd">

  <theme name="onepagewebsite">
    <vulnerability>
      <title>onepagewebsite Full Path Disclosure vulnerability</title>
      <reference>http://1337day.com/exploit/20027</reference>
      <type>FPD</type>
    </vulnerability>
  </theme>

  <theme name="vithy">
    <vulnerability>
      <title>vithy Full Path Disclosure vulnerability</title>
      <reference>http://1337day.com/exploit/20040</reference>
      <type>FPD</type>
    </vulnerability>
  </theme>

  <theme name="appius">
    <vulnerability>
      <title>appius Full Path Disclosure vulnerability</title>
      <reference>http://1337day.com/exploit/20039</reference>
      <type>FPD</type>
    </vulnerability>
  </theme>

  <theme name="yvora">
    <vulnerability>
      <title>yvora Full Path Disclosure vulnerability</title>
      <reference>http://1337day.com/exploit/20038</reference>
      <type>FPD</type>
    </vulnerability>
  </theme>

  <theme name="shotzz">
    <vulnerability>
      <title>shotzz Full Path Disclosure vulnerability</title>
      <reference>http://1337day.com/exploit/20041</reference>
      <type>FPD</type>
    </vulnerability>
  </theme>

  <theme name="moneymasters">
    <vulnerability>
      <title>moneymasters Full Path Disclosure vulnerability</title>
      <reference>http://1337day.com/exploit/20077</reference>
      <type>FPD</type>
    </vulnerability>
    <vulnerability>
      <title>moneymasters File Upload Vulnerability (metasploit)</title>
      <reference>http://1337day.com/exploit/20076</reference>
      <type>UPLOAD</type>
    </vulnerability>
  </theme>

  <theme name="ovum">
    <vulnerability>
      <title>XSS vulnerability in Imediapixel premium WordPress themes</title>
      <reference>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-imediapixel.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="avanix">
    <vulnerability>
      <title>XSS vulnerability in Imediapixel premium WordPress themes</title>
      <reference>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-imediapixel.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="ebiz">
    <vulnerability>
      <title>XSS vulnerability in Imediapixel premium WordPress themes</title>
      <reference>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-imediapixel.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="ecobiz">
    <vulnerability>
      <title>XSS vulnerability in Imediapixel premium WordPress themes</title>
      <reference>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-imediapixel.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="traject">
    <vulnerability>
      <title>XSS vulnerability in Parallelus premium WordPress themes</title>
      <reference>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-parallelus-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="intersect">
    <vulnerability>
      <title>XSS vulnerability in Parallelus premium WordPress themes</title>
      <reference>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-parallelus-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="salutation">
    <vulnerability>
      <title>XSS vulnerability in Parallelus premium WordPress themes</title>
      <reference>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-parallelus-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="unite">
    <vulnerability>
      <title>XSS vulnerability in Parallelus premium WordPress themes</title>
      <reference>http://jannefi.blogspot.fi/2012/10/xss-vulnerability-in-parallelus-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="shapeless">
    <vulnerability>
      <title>XSS vulnerability in multiple premium WordPress themes by Flow/Devatic</title>
      <reference>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="brisk">
    <vulnerability>
      <title>XSS vulnerability in multiple premium WordPress themes by Flow/Devatic</title>
      <reference>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="blaze">
    <vulnerability>
      <title>XSS vulnerability in multiple premium WordPress themes by Flow/Devatic</title>
      <reference>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="eunice">
    <vulnerability>
      <title>XSS vulnerability in multiple premium WordPress themes by Flow/Devatic</title>
      <reference>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="explicit">
    <vulnerability>
      <title>XSS vulnerability in multiple premium WordPress themes by Flow/Devatic</title>
      <reference>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="essence">
    <vulnerability>
      <title>XSS vulnerability in multiple premium WordPress themes by Flow/Devatic</title>
      <reference>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="paramount">
    <vulnerability>
      <title>XSS vulnerability in multiple premium WordPress themes by Flow/Devatic</title>
      <reference>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="picturefactory">
    <vulnerability>
      <title>XSS vulnerability in multiple premium WordPress themes by Flow/Devatic</title>
      <reference>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="sparky">
    <vulnerability>
      <title>XSS vulnerability in multiple premium WordPress themes by Flow/Devatic</title>
      <reference>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="theagency">
    <vulnerability>
      <title>XSS vulnerability in multiple premium WordPress themes by Flow/Devatic</title>
      <reference>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="konzept">
    <vulnerability>
      <title>XSS vulnerability in multiple premium WordPress themes by Flow/Devatic</title>
      <reference>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="daisho">
    <vulnerability>
      <title>XSS vulnerability in multiple premium WordPress themes by Flow/Devatic</title>
      <reference>http://jannefi.blogspot.fi/2012/09/xss-vulnerability-in-multiple-premium.html</reference>
      <type>XSS</type>
    </vulnerability>
  </theme>

  <theme name="wise">
    <vulnerability>
      <title>Site5 Wordpress Themes Email Spoofing</title>
      <reference>http://packetstormsecurity.org/files/114750/</reference>
      <type>UNKNOWN</type>
    </vulnerability>
  </theme>

  <theme name="webfolio">
    <vulnerability>
      <title>Site5 Wordpress Themes Email Spoofing</title>
      <reference>http://packetstormsecurity.org/files/114750/</reference>
      <type>UNKNOWN</type>
    </vulnerability>
  </theme>

  <theme name="colorbold">
    <vulnerability>
      <title>Site5 Wordpress Themes Email Spoofing</title>
      <reference>http://packetstormsecurity.org/files/114750/</reference>
      <type>UNKNOWN</type>
    </vulnerability>
  </theme>

  <theme name="rockwell">
    <vulnerability>
      <title>Site5 Wordpress Themes Email Spoofing</title>
      <reference>http://packetstormsecurity.org/files/114750/</reference>
      <type>UNKNOWN</type>
    </vulnerability>
  </theme>

  <theme name="xmas">
    <vulnerability>
      <title>Site5 Wordpress Themes Email Spoofing</title>
      <reference>http://packetstormsecurity.org/files/114750/</reference>
      <type>UNKNOWN</type>
    </vulnerability>
  </theme>

  <theme name="designpile">
    <vulnerability>
      <title>Site5 Wordpress Themes Email Spoofing</title>
      <reference>http://packetstormsecurity.org/files/114750/</reference>
      <type>UNKNOWN</type>
    </vulnerability>
  </theme>

  <theme name="alltuts">
    <vulnerability>
      <title>Site5 Wordpress Themes Email Spoofing</title>
      <reference>http://packetstormsecurity.org/files/114750/</reference>
      <type>UNKNOWN</type>
    </vulnerability>
  </theme>

  <theme name="boldy">
    <vulnerability>
      <title>Site5 Wordpress Themes Email Spoofing</title>
      <reference>http://packetstormsecurity.org/files/114750/</reference>
      <type>UNKNOWN</type>
    </vulnerability>
  </theme>

  <theme name="simplo">
    <vulnerability>
      <title>Site5 Wordpress Themes Email Spoofing</title>
      <reference>http://packetstormsecurity.org/files/114750/</reference>
      <type>UNKNOWN</type>
    </vulnerability>
  </theme>

  <theme name="diary">
    <vulnerability>
      <title>Site5 Wordpress Themes Email Spoofing</title>
      <reference>http://packetstormsecurity.org/files/114750/</reference>
      <type>UNKNOWN</type>
